name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install MariaDB Connector/C
      run: |
        sudo apt-get update
        sudo apt-get install -y mariadb-client libmariadb-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: sudo docker build . -t mimasiunia/filesshare:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Delete old Docker image from Docker Hub
      run: |
        REPO="mimasiunia/filesshare"
        TAG="latest"
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        MANIFEST_DIGEST=$(curl -s -H "Authorization: JWT ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://hub.docker.com/v2/repositories/${REPO}/tags/${TAG}/" | jq -r .images[0].digest)
        curl -s -H "Authorization: JWT ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${REPO}/manifests/${MANIFEST_DIGEST}"

    - name: Push Docker image to Docker Hub
      run: |
        sudo docker tag mimasiunia/filesshare:latest mimasiunia/filesshare:latest
        sudo docker push mimasiunia/filesshare:latest

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sudo chmod 666 /var/run/docker.sock
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$SERVER << EOF
          echo "$SUDO_PASSWORD" | sudo -S docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          echo "$SUDO_PASSWORD" | sudo -S docker stop filesshare || true
          echo "$SUDO_PASSWORD" | sudo -S docker rm filesshare || true
          echo "$SUDO_PASSWORD" | sudo -S docker rmi mimasiunia/filesshare:latest || true
          echo "$SUDO_PASSWORD" | sudo -S docker pull mimasiunia/filesshare:latest
          echo "$SUDO_PASSWORD" | sudo -S docker run -d --name filesshare -p 4999:4999 -v /myservices/fs/data:/app/data mimasiunia/filesshare:latest
        EOF