name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install MariaDB Connector/C
      run: |
        sudo apt-get update
        sudo apt-get install -y mariadb-client libmariadb-dev

    - name: Install dependencies for script
      run: |
        pip install -r script/requirements.txt

    - name: Run tests for script
      run: |
        pytest script/tests

    - name: Install dependencies for app
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run tests for app
      run: |
        pytest app/tests

    - name: Build Docker Compose
      run: |
        sudo docker-compose build

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Delete old Docker image for app from Docker Hub
      run: |
        REPO="mimasiunia/filesshare_app"
        TAG="latest"
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        MANIFEST_DIGEST=$(curl -s -H "Authorization: JWT ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://hub.docker.com/v2/repositories/${REPO}/tags/${TAG}/" | jq -r .images[0].digest)
        curl -s -H "Authorization: JWT ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${REPO}/manifests/${MANIFEST_DIGEST}"

    - name: Delete old Docker image for script from Docker Hub
      run: |
        REPO="mimasiunia/filesshare_script"
        TAG="latest"
        TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
        MANIFEST_DIGEST=$(curl -s -H "Authorization: JWT ${TOKEN}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "https://hub.docker.com/v2/repositories/${REPO}/tags/${TAG}/" | jq -r .images[0].digest)
        curl -s -H "Authorization: JWT ${TOKEN}" -X DELETE "https://hub.docker.com/v2/repositories/${REPO}/manifests/${MANIFEST_DIGEST}"

    - name: Push Docker images to Docker Hub
      run: |
        sudo docker push mimasiunia/filesshare_app:latest
        sudo docker push mimasiunia/filesshare_script:latest

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sudo chmod 666 /var/run/docker.sock
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$SERVER << EOF
          echo "$SUDO_PASSWORD" | sudo -S apt-get update
          echo "$SUDO_PASSWORD" | sudo -S apt-get install -y docker-compose
          echo "$SUDO_PASSWORD" | sudo -S docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin <<< "${{ secrets.DOCKER_PASSWORD }}"
          echo "$SUDO_PASSWORD" | sudo -S docker-compose down
          echo "$SUDO_PASSWORD" | sudo -S docker ps -a -q --filter name=app_container | xargs --no-run-if-empty sudo docker rm
          echo "$SUDO_PASSWORD" | sudo -S docker ps -a -q --filter name=script_container | xargs --no-run-if-empty sudo docker rm
          echo "$SUDO_PASSWORD" | sudo -S docker rmi mimasiunia/filesshare_app:latest || true
          echo "$SUDO_PASSWORD" | sudo -S docker rmi mimasiunia/filesshare_script:latest || true
          echo "$SUDO_PASSWORD" | sudo -S docker-compose pull
          echo "$SUDO_PASSWORD" | sudo -S docker-compose up -d
        EOF
