name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install MariaDB Connector/C
      run: |
        sudo apt-get update
        sudo apt-get install -y mariadb-client libmariadb-dev

    - name: Install dependencies for script
      run: |
        pip install -r script/requirements.txt

    - name: Run tests for script
      run: |
        pytest script/tests

    - name: Install dependencies for app
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run tests for app
      run: |
        pytest app/tests

    - name: Build Docker Compose
      run: |
        sudo docker-compose build

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        sudo docker tag app_container mimasiunia/filesshare_app:latest
        sudo docker tag script_container mimasiunia/filesshare_script:latest
        sudo docker push mimasiunia/filesshare_app:latest
        sudo docker push mimasiunia/filesshare_script:latest

    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
        SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sudo chmod 666 /var/run/docker.sock
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$SERVER << EOF
          echo "$SUDO_PASSWORD" | sudo -S docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          echo "$SUDO_PASSWORD" | sudo -S docker-compose down
          echo "$SUDO_PASSWORD" | sudo -S docker-compose pull
          echo "$SUDO_PASSWORD" | sudo -S docker-compose up -d
        EOF
